version: "3"
services:
    client:
     build:
       dockerfile: ./client/Dockerfile
       context: ./src
       args:
         TITLE: Social
         BACKEND_API_URL: https://social.ffsimonov.com/api
         BACKEND_URL: https://social.ffsimonov.com
     working_dir: /home/node/app/client
     expose:
       - 3000
     volumes:
       - ./src/client:/home/node/app/client
       - /home/node/app/client/node_modules/
     depends_on:
       - server
     restart: always
    server:
      build:
        dockerfile: ./server/Dockerfile
        context: ./src
      working_dir: /home/node/app/server
      command: npm run start
      environment:
        NODE_ENV: production
        PORT: 5000
        MONGO_URI: "mongodb://database:"
        MONGO_PORT: 27017
        SESS_NAME: sid
        SESS_SECRET: secret!session
        # 30 Days 30 * 1000 * 60 * 60 * 24
        SESS_LIFETIME: 2592000000
      ports:
      - 127.0.0.1:5000:5000
      volumes:
        #- ./src/server:/home/node/app/server
        - /home/node/app/server/node_modules/
      depends_on:
        - database
      restart: always
    database:
      image: mongo
      volumes:
        - ./mongodbdata:/data/db
      expose:
        - 27017
      ports:
        - 127.0.0.1:27017:27017
      restart: always
    nginx:
      image: nginx:latest
      ports:
      - 80:80
      - 443:443
      restart: always
      volumes:
      - ./src/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./src/certbot/www/:/var/www/certbot/:ro
      - ./src/certbot/conf/:/etc/nginx/ssl/:ro
      depends_on:
        - server
        - client
    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./src/certbot/www/:/var/www/certbot/:rw
        - ./src/certbot/conf/:/etc/letsencrypt/:rw
      restart: always
