services:
  # client:
  # server:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: ./src
    working_dir: /home/node/app/server
#    command: "npm run build:watch"
    # network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - ./src/server:/home/node/app/server
      - /home/node/app/server/node_modules/
  # server:
  #   image: "node:alpine"
  #   user: "user"
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./src/server:/home/node/app
  #     # - ./node_modules:/home/node/app/node_modules
  #   ports:
  #     - 8081:8081
  #   command: "npm run start"
  database:
    image: mongo
    volumes:
      - ./mongodbdata:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    logging:
      driver: "none"
    # network_mode: bridge
